#define RIGHT_EN 1
#define RIGHT_FORWARD 2
#define RIGHT_BACKWARD 3

#define LEFT_EN 4
#define LEFT_FORWARD 5
#define LEFT_BACKWARD 6

#define USS_TRIG_PIN 8
#define USS_ECHO_PIN 9

#define SERVO_PIN 10

#define SERVO_LEFT 0
#define SERVO_MIDDLE 90
#define SERVO_RIGHT 180

#define NRF24L01_ADDRESS_LENGTH 5
#define NRF24L01_ADDRESS_LENGTH_STR NRF24L01_ADDRESS_LENGTH + 1 